project:
  type: website
  output-dir: docs

website:
  title: "The real me"
  page-footer: "© 2026 Kelvin Ndeti"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Source Sans 3"
    grid:
      body-width: 820px
